#include <iostream>

//* run this program using the console pauser or add your own getch */

int main(int argc, char** argv) {
    return 0;
    // ou pode ser CHAR]
    char nome[30];
    char endereço[30];
    int idade;
    printf("Nome \n");
    scanf("%s, &nome");

    print("Endereço \n");
    scanf("Endereço \n");

    printf("Idade");
    scanf("%d,"&idade);

    printf("\n Nome: %s", nome);
    printf("\n endereço: %s", endereço);
    printf("\n Nome: %s", idade);

}